name: Splashable environment setup action
description: Sets up environments using this all-in-one composite action.
author: KTrain5169

inputs:
  language:
    description: The language to set up.
    required: true
  lang-ver:
    description: The version of the language.
    required: true
  package-manager:
    description: What package manager?
    required: true
  manager-version:
    description: What version of the package manager?
    required: true
  lockfile:
    description: Path to the lockfile/dependencies/environment file.
    required: true
  cache:
    description: Whether or not to use caching for lockfile/dependencies.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    # Setup
    - name: Cache dependency lockfile
      if: ${{ inputs.cache == true }}
      uses: actions/cache@4.0.2
      with:
        path: ${{ inputs.lockfile }}
        key: ${{ inputs.language }}-${{ inputs.lang-ver }}_${{ inputs.package-manager }}-${{ inputs.manager-version }}_dependencies_${{ inputs.lockfile }}

    - name: Check package manager and set commands
      id: pkg-checker
      run: |
        if [[ "${{ inputs.package-manager }}" == 'easy_install' ]]; then
          echo "easy_install is deprecated. You should use pip instead."
        fi
        
        if [[ "${{ inputs.package-manager }}" == 'pip' || "${{ inputs.package-manager }}" == 'setuptools' || "${{ inputs.package-manager }}" == 'easy_install' ]]; then
          echo "install-manager=pip install --upgrade pip"
          echo "install-dependencies=pip install -r ${{ inputs.lockfile }}" >> $GITHUB_OUTPUT

        elif [[ "${{ inputs.package-manager }}" == 'pipenv' ]]; then
          echo "install-manager=pip install pipenv"
          echo "install-dependencies=pipenv 
          
        elif [[ "${{ inputs.package-manager }}" == 'miniconda' || "${{ inputs.package-manager }}" == 'anaconda' ]]; then
          echo "The conda environment will be created shortly."

        elif [[ "${{ inputs.language }}" == 'python' ]]; then
          echo "install-manager=pip install ${{ inputs.package-manager }}"
          echo "install-dependencies=${{ inputs.package-manager }} install"
        fi
        
    # Setup Python and dependencies
    - name: Setup -conda managers
      if: ${{ inputs.package-manager == 'miniconda' }} || ${{ inputs.package-manager == 'anaconda' }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ inputs.lang-ver }}
        environment-file: ${{ inputs.lockfile }}
        
    - name: Setup Python
      if: ${{ inputs.language == 'python' }} && ${{ inputs.package-manager == 'miniconda' }} || ${{ inputs.language == 'python' }} && ${{ inputs.package-manager == 'anaconda' }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.lang-ver }}
        cache: ${{ inputs.package-manager }}
        
    - name: Install dependencies
      if: ${{ inputs.language == 'python' }} && ${{ inputs.package-manager == 'miniconda' }} || ${{ inputs.language == 'python' }} && ${{ inputs.package-manager == 'anaconda' }}
      run: ${{ steps.pkg-checker.outputs.install-dependencies }}
