name: Environment setups
description: Sets up environments using this all-in-one composite action.
author: KTrain5169

inputs:
  language:
    description: The language to set up.
    required: true
  lang-ver:
    description: The version of the language.
    required: true
  package-manager:
    description: What package manager?
    required: true
  manager-version:
    description: What version of the package manager?
    required: true
  lockfile:
    description: Path to the lockfile/dependencies file.
    required: true
  cache:
    description: Whether or not to use caching for lockfile/dependencies.
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    # Setup
    - name: Cache dependency lockfile
      if: ${{ inputs.cache == true }}
      uses: actions/cache@4.0.2
      with:
        path: ${{ inputs.lockfile }}
        key: ${{ inputs.language }}-${{ inputs.lang-ver }}_${{ inputs.package-manager }}-${{ inputs.manager-version }}_dependencies_${{ inputs.lockfile }}

    - name: Check package manager and set commands
      id: pkg-checker
      run: |
        if [[ "${{ inputs.package-manager }}" == 'pip' ]]; then
          echo install-dependencies=="pip install -r ${{ inputs.lockfile }}" >> $GITHUB_OUTPUT
          echo 
        
    # Setup Python and dependencies
    - name: Setup Python
      if: ${{ inputs.language == 'python' }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.lang-ver }}
        cache: ${{ inputs.package-manager }}
        
    - name: Install dependencies
      if: ${{ inputs.language == 'python' }}
      run: 
